openapi: 3.0.0
info:
  title: Travel-Journal API
  contact: {}
  version: '1.0'
servers:
- url: https://travel-journal-api.cyclic.app/api/v1
  variables: {}
paths:
  /destinations:
    post:
      tags:
      - Destinations
      summary: add destination
      operationId: adddestination
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/adddestinationrequest'
              - example:
                  country: India
                  name: Himachal
                  img: https://unsplash.com/photos/qIXdhJz7Rns
                  rating: 4
                  description: ''
            example:
              country: India
              name: Himachal
              img: https://unsplash.com/photos/qIXdhJz7Rns
              rating: 4
              description: ''
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    get:
      tags:
      - Destinations
      summary: get all destinations
      operationId: getalldestinations
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /destinations/{id}:
    parameters:
    - in: path
      name: id
      schema:
        type: string
      required: true
      description: the destination id
    get:
      tags:
      - Destinations
      summary: get destination
      operationId: getdestination
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    delete:
      tags:
      - Destinations
      summary: delete destination
      operationId: deletedestination
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    patch:
      tags:
      - Destinations
      summary: update destination
      operationId: updatedestination
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/updatedestinationrequest'
              - example:
                  name: Himachal
                  img: https://unsplash.com/photos/XW9LTxbeS9Q
                  rating: 5
                  description: ''
            example:
              name: Himachal
              img: https://unsplash.com/photos/XW9LTxbeS9Q
              rating: 5
              description: ''
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /auth/register:
    post:
      tags:
      - Auth
      summary: register user
      operationId: registeruser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/registeruserrequest'
              - example:
                  name: aks
                  email: aks@gmail.com
                  password: secret
            example:
              name: aks
              email: aks@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
      - Auth
      summary: login user
      operationId: loginuser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/loginuserrequest'
              - example:
                  email: aks@gmail.com
                  password: secret
            example:
              email: aks@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    adddestinationrequest:
      title: adddestinationrequest
      required:
      - country
      - name
      - img
      - rating
      - description
      type: object
      properties:
        country:
          type: string
        name:
          type: string
        img:
          type: string
        rating:
          type: integer
          format: int32
        description:
          type: string
      example:
        country: India
        name: Himachal
        img: https://unsplash.com/photos/qIXdhJz7Rns
        rating: 4
        description: ''
    updatedestinationrequest:
      title: updatedestinationrequest
      required:
      - name
      - img
      - rating
      - description
      type: object
      properties:
        name:
          type: string
        img:
          type: string
        rating:
          type: integer
          format: int32
        description:
          type: string
      example:
        name: Himachal
        img: https://unsplash.com/photos/XW9LTxbeS9Q
        rating: 5
        description: ''
    registeruserrequest:
      title: registeruserrequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: akshita
        email: akshita@gmail.com
        password: secret
    loginuserrequest:
      title: loginuserrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: akshita@gmail.com
        password: secret
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Auth
  description: ''
- name: Destinations
  description: ''
